version: '3.3'
services:

  fhirhl7v2demo:
    build:
      context: .
    image: fhirhl7v2demo:iris
    hostname: fhirhl7v2demo
    ports:
    - 22222:22222 # TCP Port HL7 in
    - "51773" # 51773 is the superserver default port
    - "52776:52773" # 52773 is the webserver/management portal port
    volumes:
    - type: bind
      source: ./misc
      target: /home/irisowner/irislicense
    # - type: bind
    #   source: ./sampleFiles
    #   target: /home/irisowner/src/sampleFiles
    - type: bind
      source: ./in
      target: /home/irisowner/in
    - type: bind
      source: ./out
      target: /home/irisowner/out

  fhirhl7v2ui:
    build: ./fhirhl7ui
    image: fhirhl7v2demo:ui
    depends_on:
      - fhirhl7v2demo
    ports:
      - "4201:4200"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    command: "npm run proxy"
    volumes:
    - type: bind
      source: ./fhirhl7ui/app/src/app
      target: /home/node/app/src/app

  hapi:
    container_name: hapi
    hostname: hapi
    image: hapiproject/hapi:latest
    ports:
      - "8080:8080"
    environment:
      profiles.active: r4
      spring.datasource.url: 'jdbc:postgresql://db:5432/hapi'
      spring.datasource.username: admin
      spring.datasource.password: admin
      spring.datasource.driverClassName: org.postgresql.Driver
      # - "tester.server_address=http://localhost:8080/fhir"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    # not needed for networking between containers but here for troubleshooting
    ports:
      - "5432:5432"